export const companyTypes = ["Start-ups", "Mid-sized Companies", "Large Enterprises"];

export const plans = [
	{
		planName: "Essential",
		amount: "999",
		billingPeriod: "yearly",
		talentEngagementLimit: 5,
		description: "For small companies/startups.",
		features: {
			accessToProfiles: true,
			fullProfileViews: 5,
			freeTrial: true,
		},
		actionButtonConfig: {
			label: "Start free trial",
			href: "/auth/sign-up?plan=essential",
			variant: "outline",
		},
	},
	{
		planName: "Pro",
		amount: "9,999",
		billingPeriod: "yearly",
		talentEngagementLimit: 50,
		description: "For midsize companies.",
		features: {
			accessToProfiles: true,
			fullProfileViews: 50,
			freeTrial: true,
		},
		actionButtonConfig: {
			label: "Get started",
			variant: "default",
		},
	},
	{
		planName: "Enterprise",
		amount: "Contact us",
		billingPeriod: "yearly",
		talentEngagementLimit: null,
		description: "For large enterprises. ",
		features: {
			accessToProfiles: true,
			customEngagementLimit: true,
			documentVerification: true,
			onboardingAssistance: true,
			legalSupport: true,
			freeTrial: true,
		},
		actionButtonConfig: {
			label: "Contact us",
			variant: "default",
		},
	},
];

export const industries = [
	{ label: "Manufacturing", value: "manufacturing" },
	{ label: "Engineering", value: "engineering" },
	{ label: "Healthcare", value: "healthcare" },
	{ label: "Hospitality", value: "hospitality" },
	{ label: "Government", value: "government" },
	{ label: "Policy", value: "policy" },
	{ label: "Start-ups", value: "start-ups" },
	{ label: "Business Management", value: "business-management" },
	{ label: "Social Work", value: "social-work" },
	{ label: "Non-Profit", value: "non-profit" },
];

export const workEnvironments = [
	{ label: "Remote-first", value: "remote-first" },
	{ label: "Hybrid", value: "hybrid" },
	{ label: "In-office", value: "in-office" },
	{ label: "Flexible", value: "flexible" },
];

export const teamDynamics = [
	{ label: "Close-knit teams", value: "close-knit-teams" },
	{ label: "Independent contributors", value: "independent-contributors" },
	{ label: "Mixed", value: "mixed" },
];

export const workHours = [
	{ label: "Full-time", value: "full-time" },
	{ label: "Part-time", value: "part-time" },
	{ label: "Contract", value: "contract" },
	{ label: "Freelance", value: "freelance" },
];

export const workSchedules = [
	{ label: "Standard 9-5", value: "standard-9-5" },
	{ label: "Flexible hours", value: "flexible-hours" },
	{ label: "Shift work", value: "shift-work" },
];

export const countriesWithPostalCodes = [
	"Algeria",
	"Argentina",
	"Armenia",
	"Australia",
	"Austria",
	"Azerbaijan",
	"Azores",
	"Bangladesh",
	"Belarus",
	"Belgium",
	"Bosnia",
	"Brazil",
	"Brunei",
	"Bulgaria",
	"Canada",
	"Canary Islands",
	"China, People’s Republic of",
	"Colombia",
	"Croatia",
	"Cyprus",
	"Czech Republic",
	"Denmark",
	"Ecuador",
	"England",
	"Estonia",
	"Faeroe Islands",
	"Finland",
	"France",
	"Georgia",
	"Germany",
	"Greece",
	"Greenland",
	"Guam",
	"Guernsey",
	"Holland",
	"Hungary",
	"India",
	"Indonesia",
	"Israel",
	"Italy",
	"Japan",
	"Jersey",
	"Kazakhstan",
	"Korea, South",
	"Kosrae",
	"Kyrgyzstan",
	"Latvia",
	"Liechtenstein",
	"Lithuania",
	"Luxembourg",
	"Macedonia (FYROM)",
	"Madagascar",
	"Madeira",
	"Malaysia",
	"Marshall Islands",
	"Martinique",
	"Mayotte",
	"Mexico",
	"Mongolia",
	"Montenegro",
	"Netherlands",
	"New Zealand",
	"Northern Ireland",
	"Norway",
	"Pakistan",
	"Philippines",
	"Poland",
	"Ponape",
	"Portugal",
	"Puerto Rico",
	"Reunion",
	"Russia",
	"Saudi Arabia",
	"Scotland",
	"Serbia",
	"Singapore",
	"Slovakia",
	"Slovenia",
	"South Africa",
	"Spain",
	"Sri Lanka",
	"St. Croix",
	"St. John",
	"St. Thomas",
	"Sweden",
	"Switzerland",
	"Taiwan",
	"Tajikistan",
	"Thailand",
	"Truk",
	"Tunisia",
	"Turkey",
	"Turkmenistan",
	"U.S. Virgin Islands",
	"Ukraine",
	"United Kingdom",
	"United States",
	"Uruguay",
	"Uzbekistan",
	"Vatican City State",
	"Vietnam",
	"Wales",
	"Yap",
];
