import type { Metadata } from "next";
import { headers } from "next/headers";

import { createClient } from "@/lib/store.server";

import { Toaster } from "@/components/ui/sonner";
import AuthProvider from "@/components/AuthProvider";

import Navbar from "@/components/navbar";
import Footer from "@/components/footer";

import "./globals.css";

import { User } from "@/types/auth";

import { db } from "@/db/index";
import { talentProfiles, companyProfiles } from "@/db/schema";
import { eq } from "drizzle-orm";

export const metadata: Metadata = {
	title: {
		default: "Wira",
		template: "%s | Wira",
	},
	description: "Generated by create next app",
};

export default async function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	const headersList = await headers();
	const pathname = headersList.get("x-pathname");

	const client = await createClient(); //server client

	const {
		data: { user },
	} = await client.auth.getUser();

	let initialUserState = null;

	if (user && !pathname?.startsWith("/auth") && user.email) {
		// let email: string = user.email
		initialUserState = {
			email: user.email,
			id: user.id,
			userType: user.user_metadata.userType,
		} as User;

		if (user.user_metadata.userType === "talent") {
			const talentProfile = (await db.select().from(talentProfiles).where(eq(talentProfiles.userId, user.id)))[0];
			// console.log({ talentProfile });
			if (talentProfile) {
				initialUserState.fullName = talentProfile.fullName as string;
				initialUserState.avatarUrl = talentProfile.avatarUrl;
				initialUserState.phoneNumber = talentProfile.phoneNumber;
				initialUserState.dateOfBirth = talentProfile.dateOfBirth;
			}
		}
		else if (user.user_metadata.userType === "employer") {
			const companyProfile = (await db.select().from(companyProfiles).where(eq(companyProfiles.userId, user.id)))[0];
			// console.log({ companyProfile });
			if (companyProfile) {
				initialUserState.companyName = companyProfile.companyName as string;
				initialUserState.avatarUrl = companyProfile.avatarUrl;
				initialUserState.fullName = companyProfile.contactPersonName;
			}
		}
	}

	return (
		<html lang="en">
			{/* TODO: separate this layout into two layout groups to avoid a pile of conditional rendering */}
			<body className="flex h-[100dvh] flex-col overflow-x-hidden bg-neutral-50 antialiased">
				<Navbar />
				<AuthProvider initialState={initialUserState} />
				<div className="flex h-full flex-1 flex-col py-5">{children}</div>
				{pathname == "/" && <Footer />}
				<Toaster richColors />
			</body>
		</html>
	);
}
