import type { Metadata } from "next";

import Navbar from "@/components/navbar";

import "./globals.css";

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body className="antialiased bg-neutral-100 min-h-[100dvh] flex flex-col">
				<Navbar />
				<div className="md:px-20 xl:px-60 flex-1 py-5 flex flex-col">{children}</div>
			</body>
		</html>
	);
}
